Removed override UFUNCTIONs.
Got this error while compiling after upgrading to UE 4.20:

.../EverPresent/StrangerController.h(60) : LogCompile:
  Error: SetIgnoreMoveInput: Override of UFUNCTION in parent class
  (Controller) cannot have a UFUNCTION() declaration above it; it
  will use the same parameters as the original declaration.